/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sales
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public AdminDashboard() {
        initComponents();
        fillTable();
        
    }
    
    public void fillTable() {
        String[] columnNames = {"Employee ID", "josepName"};
        
        String[][] emps = {
            {"1", "joseph"} };
        
        
        DefaultTableModel model = new DefaultTableModel(emps, columnNames);
        
        home_emp_table.setModel(model);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminDashboardPane = new javax.swing.JTabbedPane();
        adminEmpPanel = new javax.swing.JPanel();
        CancelBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        fNameEmpTF = new javax.swing.JTextField();
        lNameEmpTF = new javax.swing.JTextField();
        DOBEmpTF = new javax.swing.JTextField();
        addressEmpTF = new javax.swing.JTextField();
        phoneNoEmpTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sssEmpTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        philHEmpTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tinEmpTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pagibigEmpTf = new javax.swing.JTextField();
        statusEmpTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        positionEmpTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        immedSuppEMpTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        basicSalaryEmpTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        riceSubsidyEmpTf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        phoneAllEmpTF = new javax.swing.JTextField();
        hourlyrateTf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        gsmrTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        clothingAllTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        adminPayrolPanel = new javax.swing.JPanel();
        hourlyratePayTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        gsmrPayTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        pagibigPayTF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        philHPayTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        sssPayTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        overtimePayTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        calculatePayBtn = new javax.swing.JButton();
        cancelPayBtn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        basicSalPayTF = new javax.swing.JTextField();
        absentPayTF = new javax.swing.JTextField();
        latePayTF = new javax.swing.JTextField();
        overtimePayTF1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        payrollSummaryPane = new javax.swing.JPanel();
        hourlyRatePSTF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        gsmrPSTF = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        pagibigPSTF = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        philhPSTF = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        sssPSTF = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        overtimePSTF = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        EditPSBtn = new javax.swing.JButton();
        SavePSBtn = new javax.swing.JButton();
        CancelPSBtn = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        basicSalaryPSTF = new javax.swing.JTextField();
        absentsPSTF = new javax.swing.JTextField();
        latePSTF = new javax.swing.JTextField();
        adminAttendancePane = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        attendIDNoTF = new javax.swing.JTextField();
        attendNameTF = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        AttendanceTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dashboardName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        home_emp_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");

        adminDashboardPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        adminDashboardPane.setToolTipText("");
        adminDashboardPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminDashboardPane.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        adminDashboardPane.setName(""); // NOI18N

        CancelBtn.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        CancelBtn.setText("Cancel");

        SaveBtn.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        EditBtn.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        EditBtn.setText("Edit");

        fNameEmpTF.setEditable(false);
        fNameEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        lNameEmpTF.setEditable(false);
        lNameEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        DOBEmpTF.setEditable(false);
        DOBEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        addressEmpTF.setEditable(false);
        addressEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        phoneNoEmpTf.setEditable(false);
        phoneNoEmpTf.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel3.setText("First name");

        sssEmpTF.setEditable(false);
        sssEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        sssEmpTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssEmpTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Phone Number");

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Date of Birth");

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel8.setText("SSS No.");

        philHEmpTF.setEditable(false);
        philHEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel9.setText("PhilHealth No.");

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel10.setText("TIN No.");

        tinEmpTF.setEditable(false);
        tinEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Pag-Ibig No.");

        pagibigEmpTf.setEditable(false);
        pagibigEmpTf.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        statusEmpTF.setEditable(false);
        statusEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Status");

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Position");

        positionEmpTF.setEditable(false);
        positionEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Immediate Supervisor");

        immedSuppEMpTF.setEditable(false);
        immedSuppEMpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Basic Salary");

        basicSalaryEmpTF.setEditable(false);
        basicSalaryEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Rice Subsidy");

        riceSubsidyEmpTf.setEditable(false);
        riceSubsidyEmpTf.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel17.setText("Phone Allowance");

        phoneAllEmpTF.setEditable(false);
        phoneAllEmpTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        hourlyrateTf.setEditable(false);
        hourlyrateTf.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel18.setText("Hourly Rate");

        gsmrTF.setEditable(false);
        gsmrTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel19.setText("Gross Semi Monthly Rate");

        clothingAllTF.setEditable(false);
        clothingAllTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel20.setText("Clothing Allowance");

        javax.swing.GroupLayout adminEmpPanelLayout = new javax.swing.GroupLayout(adminEmpPanel);
        adminEmpPanel.setLayout(adminEmpPanelLayout);
        adminEmpPanelLayout.setHorizontalGroup(
            adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fNameEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(141, 141, 141)
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lNameEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addressEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DOBEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(phoneNoEmpTf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sssEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(philHEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tinEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pagibigEmpTf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(positionEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(riceSubsidyEmpTf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(phoneAllEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(clothingAllTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(gsmrTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(hourlyrateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(basicSalaryEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(immedSuppEMpTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SaveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtn)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        adminEmpPanelLayout.setVerticalGroup(
            adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNameEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basicSalaryEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                        .addComponent(riceSubsidyEmpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(DOBEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phoneNoEmpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addComponent(phoneAllEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20))
                            .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                        .addComponent(clothingAllTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gsmrTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hourlyrateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminEmpPanelLayout.createSequentialGroup()
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(philHEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sssEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tinEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(adminEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pagibigEmpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminEmpPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionEmpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EditBtn)
                                .addComponent(SaveBtn)
                                .addComponent(CancelBtn))
                            .addComponent(immedSuppEMpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        adminDashboardPane.addTab("Employees", adminEmpPanel);

        hourlyratePayTF.setEditable(false);

        jLabel21.setText("Hourly Rate");

        gsmrPayTF.setEditable(false);

        jLabel22.setText("Gross Semi Monthly Rate");

        pagibigPayTF.setEditable(false);

        jLabel23.setText("Pag-Ibig");

        philHPayTF.setEditable(false);

        jLabel24.setText("Phil-Health");

        sssPayTF.setEditable(false);

        jLabel25.setText("SSS");

        jLabel26.setText("Basic Salary");

        calculatePayBtn.setText("Calculate");
        calculatePayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatePayBtnActionPerformed(evt);
            }
        });

        cancelPayBtn.setText("Cancel");

        jLabel27.setText("Overtime");

        jLabel28.setText("Late");

        jLabel29.setText("Absent");

        basicSalPayTF.setEditable(false);

        jLabel39.setText("Withholding Tax");

        javax.swing.GroupLayout adminPayrolPanelLayout = new javax.swing.GroupLayout(adminPayrolPanel);
        adminPayrolPanel.setLayout(adminPayrolPanelLayout);
        adminPayrolPanelLayout.setHorizontalGroup(
            adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gsmrPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(hourlyratePayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                        .addGroup(adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23)
                            .addComponent(sssPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(philHPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagibigPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basicSalPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(40, 40, 40)
                        .addGroup(adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(overtimePayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(absentPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latePayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(overtimePayTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                        .addComponent(calculatePayBtn)
                        .addGap(20, 20, 20)
                        .addComponent(cancelPayBtn)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        adminPayrolPanelLayout.setVerticalGroup(
            adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basicSalPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overtimePayTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sssPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(philHPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagibigPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPayrolPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overtimePayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(latePayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(absentPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gsmrPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyratePayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(adminPayrolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatePayBtn)
                    .addComponent(cancelPayBtn))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        adminDashboardPane.addTab("Payroll", adminPayrolPanel);

        jLabel30.setText("Hourly Rate");

        jLabel31.setText("Gross Semi Monthly Rate");

        jLabel32.setText("Pag-Ibig");

        jLabel33.setText("Phil-Health");

        jLabel34.setText("SSS");

        jLabel35.setText("Basic Salary");

        EditPSBtn.setText("Edit");

        SavePSBtn.setText("Save");
        SavePSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePSBtnActionPerformed(evt);
            }
        });

        CancelPSBtn.setText("Cancel");

        jLabel36.setText("Overtime");

        jLabel37.setText("Late");

        jLabel38.setText("Absent");

        javax.swing.GroupLayout payrollSummaryPaneLayout = new javax.swing.GroupLayout(payrollSummaryPane);
        payrollSummaryPane.setLayout(payrollSummaryPaneLayout);
        payrollSummaryPaneLayout.setHorizontalGroup(
            payrollSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payrollSummaryPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(payrollSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gsmrPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(hourlyRatePSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addGroup(payrollSummaryPaneLayout.createSequentialGroup()
                        .addComponent(EditPSBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SavePSBtn)
                        .addGap(20, 20, 20)
                        .addComponent(CancelPSBtn))
                    .addGroup(payrollSummaryPaneLayout.createSequentialGroup()
                        .addGroup(payrollSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel32)
                            .addComponent(sssPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(philhPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagibigPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basicSalaryPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(47, 47, 47)
                        .addGroup(payrollSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(overtimePSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(absentsPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latePSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        payrollSummaryPaneLayout.setVerticalGroup(
            payrollSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payrollSummaryPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(payrollSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(payrollSummaryPaneLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basicSalaryPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sssPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(philhPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(payrollSummaryPaneLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(overtimePSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(latePSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(absentsPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagibigPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gsmrPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyRatePSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(payrollSummaryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditPSBtn)
                    .addComponent(SavePSBtn)
                    .addComponent(CancelPSBtn))
                .addGap(67, 67, 67))
        );

        adminDashboardPane.addTab("Payroll Summary", payrollSummaryPane);

        jLabel49.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel49.setText("ID Number");

        jLabel50.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel50.setText("Name");

        attendIDNoTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        attendNameTF.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        AttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Date and Time", "Type"
            }
        ));
        jScrollPane6.setViewportView(AttendanceTable);

        javax.swing.GroupLayout adminAttendancePaneLayout = new javax.swing.GroupLayout(adminAttendancePane);
        adminAttendancePane.setLayout(adminAttendancePaneLayout);
        adminAttendancePaneLayout.setHorizontalGroup(
            adminAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAttendancePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(adminAttendancePaneLayout.createSequentialGroup()
                        .addGroup(adminAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addGap(47, 47, 47)
                        .addGroup(adminAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attendIDNoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(attendNameTF))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminAttendancePaneLayout.setVerticalGroup(
            adminAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAttendancePaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(adminAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(attendIDNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(adminAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(attendNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        adminDashboardPane.addTab("Attendance", adminAttendancePane);

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 48)); // NOI18N
        jLabel2.setText("Welcome");

        dashboardName.setFont(new java.awt.Font("Malgun Gothic", 0, 48)); // NOI18N
        dashboardName.setText("[Name]");

        home_emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(home_emp_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dashboardName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(adminDashboardPane, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardName)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(adminDashboardPane)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void sssEmpTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssEmpTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssEmpTFActionPerformed

    private void calculatePayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatePayBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calculatePayBtnActionPerformed

    private void SavePSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePSBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavePSBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttendanceTable;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton CancelPSBtn;
    private javax.swing.JTextField DOBEmpTF;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton EditPSBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SavePSBtn;
    private javax.swing.JTextField absentPayTF;
    private javax.swing.JTextField absentsPSTF;
    private javax.swing.JTextField addressEmpTF;
    private javax.swing.JPanel adminAttendancePane;
    private javax.swing.JTabbedPane adminDashboardPane;
    private javax.swing.JPanel adminEmpPanel;
    private javax.swing.JPanel adminPayrolPanel;
    private javax.swing.JTextField attendIDNoTF;
    private javax.swing.JTextField attendNameTF;
    private javax.swing.JTextField basicSalPayTF;
    private javax.swing.JTextField basicSalaryEmpTF;
    private javax.swing.JTextField basicSalaryPSTF;
    private javax.swing.JButton calculatePayBtn;
    private javax.swing.JButton cancelPayBtn;
    private javax.swing.JTextField clothingAllTF;
    private javax.swing.JLabel dashboardName;
    private javax.swing.JTextField fNameEmpTF;
    private javax.swing.JTextField gsmrPSTF;
    private javax.swing.JTextField gsmrPayTF;
    private javax.swing.JTextField gsmrTF;
    private javax.swing.JTable home_emp_table;
    private javax.swing.JTextField hourlyRatePSTF;
    private javax.swing.JTextField hourlyratePayTF;
    private javax.swing.JTextField hourlyrateTf;
    private javax.swing.JTextField immedSuppEMpTF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField lNameEmpTF;
    private javax.swing.JTextField latePSTF;
    private javax.swing.JTextField latePayTF;
    private javax.swing.JTextField overtimePSTF;
    private javax.swing.JTextField overtimePayTF;
    private javax.swing.JTextField overtimePayTF1;
    private javax.swing.JTextField pagibigEmpTf;
    private javax.swing.JTextField pagibigPSTF;
    private javax.swing.JTextField pagibigPayTF;
    private javax.swing.JPanel payrollSummaryPane;
    private javax.swing.JTextField philHEmpTF;
    private javax.swing.JTextField philHPayTF;
    private javax.swing.JTextField philhPSTF;
    private javax.swing.JTextField phoneAllEmpTF;
    private javax.swing.JTextField phoneNoEmpTf;
    private javax.swing.JTextField positionEmpTF;
    private javax.swing.JTextField riceSubsidyEmpTf;
    private javax.swing.JTextField sssEmpTF;
    private javax.swing.JTextField sssPSTF;
    private javax.swing.JTextField sssPayTF;
    private javax.swing.JTextField statusEmpTF;
    private javax.swing.JTextField tinEmpTF;
    // End of variables declaration//GEN-END:variables
}
