/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MotorPH_OOP;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sales
 */
public class EmployeeDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public EmployeeDashboard() {
        initComponents();
        fillTable();
        
    }
    
    public void fillTable() {
        String[] columnNames = {"Employee ID", "josepName"};
        
        String[][] emps = {
            {"1", "joseph"} };
        
        
        DefaultTableModel model = new DefaultTableModel(emps, columnNames);
        
        home_emp_table.setModel(model);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empDashboardPane = new javax.swing.JTabbedPane();
        empPayslipPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        deductionsTable1 = new javax.swing.JTable();
        empDeductionsPane = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        deductionsTable = new javax.swing.JTable();
        empOvertimePane = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        overtimeTable = new javax.swing.JTable();
        empAttendancePane = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        AttendanceTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dashboardName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        home_emp_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");

        empDashboardPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        empDashboardPane.setToolTipText("");
        empDashboardPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        empDashboardPane.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        empDashboardPane.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel3.setText("ID Number");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Name");

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Date of Birth");

        jTextField37.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jTextField38.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jTextField39.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        deductionsTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Basic Salary", "Gross Earnings", "Withholding Tax", "SSS", "Pag-Ibig", "Phil-Health", "Title 7", "Title 8"
            }
        ));
        jScrollPane7.setViewportView(deductionsTable1);

        javax.swing.GroupLayout empPayslipPaneLayout = new javax.swing.GroupLayout(empPayslipPane);
        empPayslipPane.setLayout(empPayslipPaneLayout);
        empPayslipPaneLayout.setHorizontalGroup(
            empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPayslipPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empPayslipPaneLayout.createSequentialGroup()
                        .addGroup(empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField37, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextField39)
                            .addComponent(jTextField38))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
                .addContainerGap())
        );
        empPayslipPaneLayout.setVerticalGroup(
            empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPayslipPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(empPayslipPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        empDashboardPane.addTab("Payslips", empPayslipPane);

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel15.setText("ID Number");

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Name");

        jTextField40.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jTextField42.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        deductionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Deductions", "Amount"
            }
        ));
        jScrollPane4.setViewportView(deductionsTable);

        javax.swing.GroupLayout empDeductionsPaneLayout = new javax.swing.GroupLayout(empDeductionsPane);
        empDeductionsPane.setLayout(empDeductionsPaneLayout);
        empDeductionsPaneLayout.setHorizontalGroup(
            empDeductionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empDeductionsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empDeductionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(empDeductionsPaneLayout.createSequentialGroup()
                        .addGroup(empDeductionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(47, 47, 47)
                        .addGroup(empDeductionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField40, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextField42))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        empDeductionsPaneLayout.setVerticalGroup(
            empDeductionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empDeductionsPaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(empDeductionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(empDeductionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        empDashboardPane.addTab("Deductions", empDeductionsPane);

        jLabel18.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel18.setText("ID Number");

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel19.setText("Name");

        jTextField43.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jTextField44.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        overtimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Hours"
            }
        ));
        jScrollPane5.setViewportView(overtimeTable);

        javax.swing.GroupLayout empOvertimePaneLayout = new javax.swing.GroupLayout(empOvertimePane);
        empOvertimePane.setLayout(empOvertimePaneLayout);
        empOvertimePaneLayout.setHorizontalGroup(
            empOvertimePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empOvertimePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empOvertimePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(empOvertimePaneLayout.createSequentialGroup()
                        .addGroup(empOvertimePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(47, 47, 47)
                        .addGroup(empOvertimePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField43, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextField44))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        empOvertimePaneLayout.setVerticalGroup(
            empOvertimePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empOvertimePaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(empOvertimePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(empOvertimePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        empDashboardPane.addTab("Overtime", empOvertimePane);

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel20.setText("ID Number");

        jLabel30.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel30.setText("Name");

        jTextField45.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jTextField46.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        AttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Date and Time", "Type"
            }
        ));
        jScrollPane6.setViewportView(AttendanceTable);

        javax.swing.GroupLayout empAttendancePaneLayout = new javax.swing.GroupLayout(empAttendancePane);
        empAttendancePane.setLayout(empAttendancePaneLayout);
        empAttendancePaneLayout.setHorizontalGroup(
            empAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empAttendancePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(empAttendancePaneLayout.createSequentialGroup()
                        .addGroup(empAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel30))
                        .addGap(47, 47, 47)
                        .addGroup(empAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField45, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextField46))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        empAttendancePaneLayout.setVerticalGroup(
            empAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empAttendancePaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(empAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(empAttendancePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        empDashboardPane.addTab("Attendance", empAttendancePane);

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 48)); // NOI18N
        jLabel2.setText("Welcome");

        dashboardName.setFont(new java.awt.Font("Malgun Gothic", 0, 48)); // NOI18N
        dashboardName.setText("[Name]");

        home_emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(home_emp_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dashboardName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(empDashboardPane, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardName)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(empDashboardPane, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttendanceTable;
    private javax.swing.JLabel dashboardName;
    private javax.swing.JTable deductionsTable;
    private javax.swing.JTable deductionsTable1;
    private javax.swing.JPanel empAttendancePane;
    private javax.swing.JTabbedPane empDashboardPane;
    private javax.swing.JPanel empDeductionsPane;
    private javax.swing.JPanel empOvertimePane;
    private javax.swing.JPanel empPayslipPane;
    private javax.swing.JTable home_emp_table;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTable overtimeTable;
    // End of variables declaration//GEN-END:variables
}
